language: python

python:
  - "2.7"

sudo: false
cache: pip

git:
  submodules: false

addons:
  postgresql: "9.2" # minimal postgresql version for the daterange method
  apt:
    packages:
      - expect-dev
      - python-lxml
      # - unixodbc-dev

before_install:
  - git clone https://github.com/zeroincombenze/tools.git ${HOME}/tools --depth=1
  - mv ${HOME}/tools/maintainer-quality-tools ${HOME}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_env oca

install:
  # - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  # - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  # - travis_install_nightly

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="0"
  # - TRANSIFEX="0"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="zeroincombenze/OCB"

virtualenv:
  system_site_packages: true

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
