language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/OCA/account-invoicing $HOME/account-invoicing -b 7.0
  - git clone https://github.com/OCA/account-financial-tools $HOME/account-financial-tools -b 7.0
  - git clone https://github.com/OCA/webkit-tools $HOME/webkit-tools -b 7.0
  - git clone https://github.com/OCA/account-payment $HOME/account-payment -b 7.0

install:
 - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
 - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
 - $HOME/maintainer-quality-tools/travis/travis_install_nightly 7.0
 - pip install coveralls flake8
 - pip install unidecode==0.04.17
 - pip install PyXB==1.2.4

services:
  - postgresql

script:
    - travis_run_flake8
    - travis_run_tests 7.0 $HOME/account-invoicing $HOME/account-financial-tools $HOME/webkit-tools $HOME/account-payment

after_success:
  coveralls
