language: python

python:
  - "2.7"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="7.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: ABaQffZycmzdJs9Slg4OLC8K+wnmpkS5R7bEIOAgsZYMYnOntZz6SzhF8/TOqI2hdUyvxgyVLhUlZdLrgogUgG/V2QjdmIErE6+x4iHECgQ4iXvhqtTpN2S/SVyjVP+7QE8Ugnth/tykWxXpgMpkuA6xnGC2HU8r/s4261tys4g=

  matrix:
  - LINT_CHECK="0"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install unidecode
  - pip install PyXB==1.2.4
  - pip install codicefiscale

script:
  # Patch to avoid failing due error in official Odoo/OCA repository
  - : ${ODOO_REPO:="odoo/odoo"}  # default value, if not set
  - IFS="/" read -a REPO <<< "${ODOO_REPO}"
  - export REMOTE="${REPO[0],,}"
  - export REPO_NAME="${REPO[1]}"
  - export BRANCH="${VERSION}"
  - export ODOO_PATH=${HOME}/$REPO_NAME-$BRANCH
  - ln -s ${ODOO_PATH}/addons/decimal_precision ./openerp
  # End od patch
  - travis_run_tests

after_success:
  - travis_after_tests_success
